brew install \
    git \
    yarn \
    sqlite \
    git-extras \
    fish \
    lazygit \
    neofetch \
    nvm \
    starship \
    bitwarden \
    deepl \
    font-source-code-pro \
    google-chrome \
    gpg-suite \
    jetbrains-toolbox \
    kitty \
    pocket-casts \
    raycast \
    spotify \
    todoist \
    visual-studio-code \
    whatsapp \